// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFLzpIoPvkY-O34vibx_vmEmGndHfOvvI',
    appId: '1:297988313984:web:6e48e033fa53aa5fc62765',
    messagingSenderId: '297988313984',
    projectId: 'crypto-list-app-be05c',
    authDomain: 'crypto-list-app-be05c.firebaseapp.com',
    storageBucket: 'crypto-list-app-be05c.firebasestorage.app',
    measurementId: 'G-354QVHLJV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-cMfsYu4ubwf2QcGdzy1HVt82oI4VjZU',
    appId: '1:297988313984:android:4f6728f3dd5366abc62765',
    messagingSenderId: '297988313984',
    projectId: 'crypto-list-app-be05c',
    storageBucket: 'crypto-list-app-be05c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-v1sArJda1BCH6H0D_0m_sTLdCEkGUkw',
    appId: '1:297988313984:ios:424e8d7bb3216ae9c62765',
    messagingSenderId: '297988313984',
    projectId: 'crypto-list-app-be05c',
    storageBucket: 'crypto-list-app-be05c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-v1sArJda1BCH6H0D_0m_sTLdCEkGUkw',
    appId: '1:297988313984:ios:424e8d7bb3216ae9c62765',
    messagingSenderId: '297988313984',
    projectId: 'crypto-list-app-be05c',
    storageBucket: 'crypto-list-app-be05c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFLzpIoPvkY-O34vibx_vmEmGndHfOvvI',
    appId: '1:297988313984:web:03f2834f6fcc4bbdc62765',
    messagingSenderId: '297988313984',
    projectId: 'crypto-list-app-be05c',
    authDomain: 'crypto-list-app-be05c.firebaseapp.com',
    storageBucket: 'crypto-list-app-be05c.firebasestorage.app',
    measurementId: 'G-RGHKYKCXMH',
  );
}
